import "./globals.css";
import type { Metadata } from "next";
import Header from "./components/header";
import Sidebar from "./components/sidebar";
import classes from "./loggedIn.module.css";
import { getLoggedInUser } from "../utils/server/functions";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    loggedIn,
    notLoggedIn,
}: {
    loggedIn: React.ReactNode;
    notLoggedIn: React.ReactNode;
}) {
    const loggedInUser = await getLoggedInUser();

    function renderUnauthed() {
        return notLoggedIn;
    }

    function renderAuthed() {
        return (
            <div className={classes.loggedIn}>
                <Header />
                <Sidebar />
                <main className={classes.main}>{loggedIn}</main>
            </div>
        );
    }

    return (
        <html lang="en">
            <body>{loggedInUser ? renderAuthed() : renderUnauthed()}</body>
        </html>
    );
}
