import "./globals.css";
import type { Metadata } from "next";
import SessionProvider from "./SessionProvider";
import { getServerSession } from "next-auth/next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession();

    console.log(session);

    return (
        <html lang="en">
            <body>
                <SessionProvider session={session}>{children}</SessionProvider>
            </body>
        </html>
    );
}
